// <auto-generated />
namespace SF.Repositoriy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class edituser_2017012303 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edituser_2017012303));
        
        string IMigrationMetadata.Id
        {
            get { return "201701230709451_edit-user_2017012303"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
